{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.now";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.now/-/lodash.now-2.4.1.tgz";
      sha1 = "6872156500525185faf96785bb7fe7fe15b562c6";
    };
    deps = with nodePackages; [
      lodash-_isnative_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.now` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }