{ brokenPackage, buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash-node";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash-node/-/lodash-node-2.4.1.tgz";
      sha1 = "ea82f7b100c733d1a42af76801e506105e2a80ec";
    };
    deps = [];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "A collection of Lo-Dash methods as Node.js modules generated by lodash-cli.";
      keywords = [
        "customize"
        "functional"
        "lodash"
        "modules"
        "server"
        "util"
      ];
    };
  }