{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.keys";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.keys/-/lodash.keys-2.4.1.tgz";
      sha1 = "48dea46df8ff7632b10d706b8acb26591e2b3727";
    };
    deps = with nodePackages; [
      lodash-_isnative_2-4-1
      lodash-isobject_2-4-1
      lodash-_shimkeys_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.keys` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }