{ brokenPackage, buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.defaults";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.defaults/-/lodash.defaults-2.4.1.tgz";
      sha1 = "a7e8885f05e68851144b6e12a8f3678026bc4c54";
    };
    deps = with nodePackages; [
      lodash-keys_2-4-1
      lodash-_objecttypes_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.defaults` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }