{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash._escapestringchar";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/lodash._escapestringchar/-/lodash._escapestringchar-2.4.1.tgz";
      sha1 = "ecfe22618a2ade50bfeea43937e51df66f0edb72";
    };
    deps = [];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The internal Lo-Dash function `escapeStringChar` as a Node.js module generated by lodash-cli.";
    };
  }
