{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.template";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.template/-/lodash.template-2.4.1.tgz";
      sha1 = "9e611007edf629129a974ab3c48b817b3e1cf20d";
    };
    deps = with nodePackages; [
      lodash-keys_2-4-1
      lodash-defaults_2-4-1
      lodash-values_2-4-1
      lodash-_reinterpolate_2-4-1
      lodash-templatesettings_2-4-1
      lodash-_escapestringchar_2-4-1
      lodash-escape_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.template` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }