{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.templatesettings";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/lodash.templatesettings/-/lodash.templatesettings-2.4.1.tgz";
      sha1 = "ea76c75d11eb86d4dbe89a83893bb861929ac699";
    };
    deps = with nodePackages; [
      lodash-_reinterpolate_2-4-1
      lodash-escape_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash object `_.templateSettings` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }
