{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.debounce";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.debounce/-/lodash.debounce-2.4.1.tgz";
      sha1 = "d8cead246ec4b926e8b85678fc396bfeba8cc6fc";
    };
    deps = with nodePackages; [
      lodash-now_2-4-1
      lodash-isobject_2-4-1
      lodash-isfunction_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.debounce` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }