{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash._reunescapedhtml";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/lodash._reunescapedhtml/-/lodash._reunescapedhtml-2.4.1.tgz";
      sha1 = "747c4fc40103eb3bb8a0976e571f7a2659e93ba7";
    };
    deps = with nodePackages; [
      lodash-keys_2-4-1
      lodash-_htmlescapes_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The internal Lo-Dash variable `reUnescapedHtml` as a Node.js module generated by lodash-cli.";
    };
  }
