{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash._escapehtmlchar";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/lodash._escapehtmlchar/-/lodash._escapehtmlchar-2.4.1.tgz";
      sha1 = "df67c3bb6b7e8e1e831ab48bfa0795b92afe899d";
    };
    deps = with nodePackages; [
      lodash-_htmlescapes_2-4-1
    ];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The internal Lo-Dash function `escapeHtmlChar` as a Node.js module generated by lodash-cli.";
    };
  }
