{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "file-type";
    version = "3.3.0";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/file-type/-/file-type-3.3.0.tgz";
      sha1 = "3e86dcf2f5b36a00880ef9f5a190e81d249ce379";
    };
    deps = [];
    meta = {
      homepage = "https://github.com/sindresorhus/file-type";
      description = "Detect the file type of a Buffer/Uint8Array";
      keywords = [
        "mime"
        "file"
        "type"
        "archive"
        "image"
        "img"
        "pic"
        "picture"
        "flash"
        "photo"
        "video"
        "type"
        "detect"
        "check"
        "is"
        "exif"
        "exe"
        "binary"
        "buffer"
        "uint8array"
        "jpg"
        "png"
        "gif"
        "webp"
        "cr2"
        "tif"
        "bmp"
        "jxr"
        "psd"
        "zip"
        "tar"
        "rar"
        "gz"
        "bz2"
        "7z"
        "dmg"
        "mp4"
        "m4v"
        "mid"
        "mkv"
        "webm"
        "mov"
        "avi"
        "mpg"
        "mp3"
        "m4a"
        "ogg"
        "flac"
        "wav"
        "amr"
        "pdf"
        "epub"
        "exe"
        "swf"
        "rtf"
        "woff"
        "woff2"
        "eot"
        "ttf"
        "otf"
        "ico"
        "flv"
        "ps"
        "xz"
        "sqlite"
        "xpi"
        "cab"
        "deb"
        "ar"
        "Z"
        "lz"
      ];
    };
  }