{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "lodash.isfunction";
    version = "2.4.1";
    src = pkgs.fetchurl {
      url = "http://registry.npmjs.org/lodash.isfunction/-/lodash.isfunction-2.4.1.tgz";
      sha1 = "2cfd575c73e498ab57e319b77fa02adef13a94d1";
    };
    deps = [];
    devDependencies = [];
    meta = {
      homepage = "http://lodash.com/custom-builds";
      description = "The Lo-Dash function `_.isFunction` as a Node.js module generated by lodash-cli.";
      keywords = [
        "functional"
        "lodash"
        "lodash-modularized"
        "server"
        "util"
      ];
    };
  }